
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
/// <summary>
/// Ability: ALFire
/// </summary>
public sealed partial class ALFire : AbilityLogicBase
{
    public ALFire(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Param"].IsObject) { throw new SerializationException(); }  Param = global::cfg.XParamString.DeserializeXParamString(_buf["Param"]);  }
    }

    public static ALFire DeserializeALFire(JSONNode _buf)
    {
        return new ALFire(_buf);
    }

    /// <summary>
    /// 参数
    /// </summary>
    public readonly XParamString Param;
   
    public const int __ID__ = 1933272321;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Param?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Param:" + Param + ","
        + "}";
    }
}
}

