
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
/// <summary>
/// Ability: ALProjectileHit
/// </summary>
public sealed partial class ALProjectileHit : AbilityLogicBase
{
    public ALProjectileHit(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Param"].IsObject) { throw new SerializationException(); }  Param = global::cfg.XParamInt.DeserializeXParamInt(_buf["Param"]);  }
    }

    public static ALProjectileHit DeserializeALProjectileHit(JSONNode _buf)
    {
        return new ALProjectileHit(_buf);
    }

    /// <summary>
    /// 参数
    /// </summary>
    public readonly XParamInt Param;
   
    public const int __ID__ = -421354881;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Param?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Param:" + Param + ","
        + "}";
    }
}
}

