
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
/// <summary>
/// Ability: ALWeaponLockTarget
/// </summary>
public sealed partial class ALWeaponLockTarget : AbilityLogicBase
{
    public ALWeaponLockTarget(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Param"].IsObject) { throw new SerializationException(); }  Param = global::cfg.XParamNone.DeserializeXParamNone(_buf["Param"]);  }
    }

    public static ALWeaponLockTarget DeserializeALWeaponLockTarget(JSONNode _buf)
    {
        return new ALWeaponLockTarget(_buf);
    }

    /// <summary>
    /// 参数
    /// </summary>
    public readonly XParamNone Param;
   
    public const int __ID__ = -487614429;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        Param?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Param:" + Param + ","
        + "}";
    }
}
}

