
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
public partial class Tbunit
{
    private readonly System.Collections.Generic.Dictionary<int, unit> _dataMap;
    private readonly System.Collections.Generic.List<unit> _dataList;
    
    public Tbunit(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, unit>(count);
        _dataList = new System.Collections.Generic.List<unit>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            unit _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.unit.Deserializeunit(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, unit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<unit> DataList => _dataList;

    public unit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public unit Get(int key) => _dataMap[key];
    public unit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

