
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg
{
public sealed partial class unit : Luban.BeanBase
{
    public unit(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
        { if(!_buf["ASCID"].IsNumber) { throw new SerializationException(); }  ASCID = _buf["ASCID"]; }
    }

    public static unit Deserializeunit(JSONNode _buf)
    {
        return new unit(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// ASCID
    /// </summary>
    public readonly int ASCID;
   
    public const int __ID__ = 3594628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "ASCID:" + ASCID + ","
        + "}";
    }
}
}

